# Generated by Django 4.2.6 on 2023-10-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('short_des', models.TextField()),
                ('long_des', models.TextField()),
                ('product_condition', models.TextField()),
                ('seller_type', models.TextField()),
                ('seller_department', models.TextField()),
                ('borrow_amount', models.TextField()),
                ('buy_amount', models.TextField()),
                ('seller_comment', models.TextField()),
                ('seller_name', models.TextField()),
                ('seller_mail', models.TextField()),
                ('product_img', models.TextField()),
            ],
        ),
    ]
