# Generated by Django 4.2.6 on 2023-11-03 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pr_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
