# Generated by Django 4.2.6 on 2023-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_pr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='product_views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
