# Generated by Django 4.2.6 on 2023-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_details_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='interactions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
